### ISSUE TITLE
Is it possible to make network requests?

### ISSUE THREAD

**Issue by velios** [tianfangyetan1/BaseConverter_MiBand9#1]
Hi. First of all thx for amazing samples. Unfortunately i'm not understand Chineese. But if you know is it possible to make http requests through Vela than can you make simple example with that. I tried to use [system.fetch](https://iot.mi.com/vela/quickapp/zh/features/network/fetch.html) api, but unfortunately it is not work. Maybe you know another way to do it.

**Comment by tianfangyetan1** [comment]
well, it is supported on the vela app, but not on mi smart band 9.

you can find it in the [development documentation](https://iot.mi.com/vela/quickapp/zh/features/network/fetch.html#%E6%94%AF%E6%8C%81%E6%98%8E%E7%BB%86)

![屏幕截图(49)](https://github.com/user-attachments/assets/d41d7f6d-a6b1-46b3-a1be-c03966e174a1)
(machine translate by google)

**Comment by velios** [comment]
Thx for answer. It wasn't clear because i look to another projects and for example [HyperBilibili](https://github.com/OnDriveLine/HyperBilibili_Band/tree/MB9P) looks like work on Xiaomi Mi Band 9 Pro(MB9P), but in docs Xiaomi Mi Band 8 Pro(MB8P) marks as not supported. And no word about support Xiaomi Smart Band 8/9 at all.

So only way for now is to use [interconnect](https://iot.mi.com/vela/quickapp/zh/features/network/interconnect.html) api, but it seems much harder than fetch and involve android dev. 

Let's hope that the developers will add support in the future fetch api for Xiaomi Smart Band 8/9.
Thx for answer and you awesome example. Issue may be closed.
